/**
 * Debug Facebook API to see what's happening
 */

import axios from 'axios'

async function debugFacebookAPI(userAccessToken: string) {
  console.log('\n🔍 Debugging Facebook API Connection...\n')

  try {
    // Test 1: Check token info
    console.log('1️⃣ Testing token validity...')
    const debugResponse = await axios.get('https://graph.facebook.com/v22.0/debug_token', {
      params: {
        input_token: userAccessToken,
        access_token: `${process.env.INSTAGRAM_APP_ID}|${process.env.INSTAGRAM_APP_SECRET}`,
      },
    })

    console.log('✅ Token is valid')
    console.log('   App ID:', debugResponse.data.data.app_id)
    console.log('   User ID:', debugResponse.data.data.user_id)
    console.log('   Scopes:', debugResponse.data.data.scopes)
    console.log('')

    // Test 2: Get user info
    console.log('2️⃣ Getting user information...')
    const userResponse = await axios.get('https://graph.facebook.com/v22.0/me', {
      params: {
        fields: 'id,name,email',
        access_token: userAccessToken,
      },
    })

    console.log('✅ User:', userResponse.data.name)
    console.log('   ID:', userResponse.data.id)
    console.log('   Email:', userResponse.data.email || 'N/A')
    console.log('')

    // Test 3: Get Facebook Pages
    console.log('3️⃣ Fetching Facebook Pages...')
    const pagesResponse = await axios.get('https://graph.facebook.com/v22.0/me/accounts', {
      params: {
        access_token: userAccessToken,
      },
    })

    console.log('   Raw response:', JSON.stringify(pagesResponse.data, null, 2))

    if (pagesResponse.data.data && pagesResponse.data.data.length > 0) {
      console.log(`\n✅ Found ${pagesResponse.data.data.length} page(s):\n`)

      for (const page of pagesResponse.data.data) {
        console.log(`📄 ${page.name} (ID: ${page.id})`)
        console.log(`   Category: ${page.category || 'N/A'}`)
        console.log(`   Access Token: ${page.access_token ? '✓ Present' : '✗ Missing'}`)

        // Check for Instagram Business Account
        try {
          const igCheckResponse = await axios.get(`https://graph.facebook.com/v22.0/${page.id}`, {
            params: {
              fields: 'instagram_business_account',
              access_token: page.access_token,
            },
          })

          if (igCheckResponse.data.instagram_business_account) {
            console.log(`   ✅ Instagram Business Account: ${igCheckResponse.data.instagram_business_account.id}`)
          } else {
            console.log('   ⚠️  No Instagram Business Account linked')
          }
        } catch (error: any) {
          console.log('   ❌ Error checking Instagram:', error.response?.data?.error?.message || error.message)
        }

        console.log('')
      }
    } else {
      console.log('❌ No pages found!')
      console.log('')
      console.log('💡 Possible reasons:')
      console.log('   1. You are not an admin/manager of any Facebook Page')
      console.log('   2. The token was generated by a different Facebook account')
      console.log('   3. The "pages_show_list" permission was not granted')
      console.log('')
      console.log('🔧 Solutions:')
      console.log('   1. Make sure you are logged into the correct Facebook account')
      console.log('   2. Go to your Facebook Page → Settings → Page roles')
      console.log('   3. Make sure your account is listed as Admin or Editor')
      console.log('   4. Regenerate the token while logged in as that account')
      console.log('')
    }

  } catch (error: any) {
    console.error('❌ Error:', error.response?.data || error.message)

    if (error.response?.data?.error?.code === 190) {
      console.log('\n💡 Token is invalid or expired. Please generate a new one.')
    }
  }
}

const token = process.argv[2]

if (!token) {
  console.log('Usage: npm run debug-facebook YOUR_ACCESS_TOKEN')
  process.exit(1)
}

debugFacebookAPI(token)
