name: Daily Database Backup

on:
  schedule:
    # Run at 2:00 AM UTC every day
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger from GitHub Actions tab

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backup endpoint
        run: |
          curl -X POST "${{ secrets.BACKUP_ENDPOINT_URL }}" \
            -H "Content-Type: application/json" \
            -w "\nHTTP Status: %{http_code}\n" \
            -o response.json

          echo "Response:"
          cat response.json

          # Check if request was successful
          if [ $? -eq 0 ]; then
            echo "✅ Backup triggered successfully"
          else
            echo "❌ Backup trigger failed"
            exit 1
          fi

      - name: Upload response as artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: backup-response-${{ github.run_number }}
          path: response.json
          retention-days: 7
